#Minecraft server properties
accepts-transfers=true
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
difficulty=normal
enable-command-block=true
enable-jmx-monitoring=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=true
entity-broadcast-range-percentage=300
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
level-name=world
level-type=minecraft\:normal
max-chained-neighbor-updates=1000000
max-players=64
max-tick-time=120000
max-world-size=150000
motd=§r                   §x§F§C§0§0§F§FD§x§F§7§0§3§F§Da §x§E§C§0§9§F§AB§x§E§7§0§B§F§8u§x§E§2§0§E§F§6s§x§D§C§1§1§F§4i§x§D§7§1§4§F§2n§x§D§2§1§7§F§0e§x§C§D§1§A§E§Fs§x§C§7§1§C§E§Ds §x§B§D§2§2§E§9S§x§B§7§2§5§E§7e§x§B§2§2§8§E§5r§x§A§D§2§B§E§4v§x§A§8§2§D§E§2e§x§A§2§3§0§E§0r§x§9§D§3§3§D§E.\n§r  §x§F§F§E§E§0§0G§x§F§D§E§9§0§3e§x§F§B§E§4§0§6t §x§F§7§D§A§0§Cy§x§F§5§D§6§0§Fo§x§F§3§D§1§1§2u§x§F§1§C§C§1§5r §x§E§E§C§2§1§Bs§x§E§C§B§D§1§Ee§x§E§A§B§8§2§1r§x§E§8§B§3§2§4v§x§E§6§A§F§2§7e§x§E§4§A§A§2§Ar §x§E§0§A§0§3§0a§x§D§E§9§B§3§3t §x§E§B§5§4§F§4§nh§x§E§5§5§4§F§1§no§x§D§E§5§4§E§E§ns§x§D§8§5§4§E§B§nt§x§D§2§5§4§E§8§n.§x§C§C§5§4§E§5§nd§x§C§5§5§4§E§1§na§x§B§F§5§4§D§E§nb§x§B§9§5§4§D§B§nu§x§B§2§5§4§D§8§ns§x§A§C§5§4§D§5§ni§x§A§6§5§4§D§2§nn§x§9§F§5§4§C§F§ne§x§9§9§5§4§C§C§ns§x§9§3§5§4§C§9§ns§x§8§D§5§4§C§6§n.§x§8§6§5§4§C§2§nc§x§8§0§5§4§B§F§nl§x§7§A§5§4§B§C§no§x§7§3§5§4§B§9§nu§x§6§D§5§4§B§6§nd
online-mode=true
pvp=true
server-ip=0.0.0.0
server-name=dabuisiness
simulation-distance=12
spawn-protection=0
sync-chunk-writes=false
view-distance=12
white-list=true
