#Minecraft server properties
accepts-transfers=true
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
difficulty=normal
enable-command-block=true
enable-jmx-monitoring=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=true
entity-broadcast-range-percentage=300
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
level-name=world
level-type=minecraft\:normal
max-chained-neighbor-updates=1000000
max-players=64
max-tick-time=120000
max-world-size=150000
motd=§r                   §x§F§C§0§0§F§FD§x§F§7§0§3§F§Da §x§E§C§0§9§F§AB§x§E§7§0§B§F§8u§x§E§2§0§E§F§6s§x§D§C§1§1§F§4i§x§D§7§1§4§F§2n§x§D§2§1§7§F§0e§x§C§D§1§A§E§Fs§x§C§7§1§C§E§Ds §x§B§D§2§2§E§9S§x§B§7§2§5§E§7e§x§B§2§2§8§E§5r§x§A§D§2§B§E§4v§x§A§8§2§D§E§2e§x§A§2§3§0§E§0r§x§9§D§3§3§D§E.\n§r  §x§F§F§E§E§0§0G§x§F§D§E§9§0§3e§x§F§B§E§4§0§6t §x§F§7§D§A§0§Cy§x§F§5§D§6§0§Fo§x§F§3§D§1§1§2u§x§F§1§C§C§1§5r §x§E§E§C§2§1§Bs§x§E§C§B§D§1§Ee§x§E§A§B§8§2§1r§x§E§8§B§3§2§4v§x§E§6§A§F§2§7e§x§E§4§A§A§2§Ar §x§E§0§A§0§3§0a§x§D§E§9§B§3§3t §x§F§F§0§0§E§E§l§o§np§x§F§8§0§2§E§D§l§o§na§x§F§2§0§5§E§C§l§o§nn§x§E§B§0§7§E§C§l§o§ne§x§E§5§0§A§E§B§l§o§nl§x§D§E§0§C§E§A§l§o§n.§x§D§7§0§F§E§9§l§o§nd§x§D§1§1§1§E§9§l§o§na§x§C§A§1§3§E§8§l§o§nb§x§C§3§1§6§E§7§l§o§nu§x§B§D§1§8§E§6§l§o§ns§x§B§6§1§B§E§6§l§o§ni§x§B§0§1§D§E§5§l§o§nn§x§A§9§2§0§E§4§l§o§ne§x§A§2§2§2§E§3§l§o§ns§x§9§C§2§4§E§3§l§o§ns§x§9§5§2§7§E§2§l§o§n.§x§8§E§2§9§E§1§l§o§nc§x§8§8§2§C§E§0§l§o§nl§x§8§1§2§E§E§0§l§o§no§x§7§B§3§1§D§F§l§o§nu§x§7§4§3§3§D§E§l§o§nd
online-mode=true
pvp=true
server-ip=0.0.0.0
server-name=dabuisiness
simulation-distance=12
spawn-protection=0
sync-chunk-writes=false
view-distance=12
white-list=true