
config-version: '3.0'

async:
  async-chunk-send:
    enabled: true
  async-mob-spawning:
    enabled: true
  async-pathfinding:
    enabled: true
    max-threads: 8
    keepalive: 60
    queue-size: 512
    reject-policy: CALLER_RUNS
  async-playerdata-save:
    enabled: true
  async-entity-tracker:
    enabled: true
    threads: 4
  parallel-world-ticking:
    enabled: true
    threads: 8
    log-container-creation-stacktraces: false
    disable-hard-throw: false
    async-unsafe-read-handling: LOG_WARNING

performance:
  check-survival-before-growth:
    cactus-check-survival: true
  despawn-time:
    proactive-weak-loading-despawn: true
  dont-save-entity:
    dont-save-primed-tnt: true
    dont-save-falling-block: true
  dab:
    enabled: true
    dont-enable-if-in-water: true
    start-distance: 12
    max-tick-freq: 20
    activation-dist-mod: 8
    blacklisted-entities:
    - villager
    - axolotl
    - hoglin
    - zombified_piglin
    - goat
  enable-cached-minecraft-to-bukkit-entitytype-convert: true
  entity-goal:
    start-tick-chance:
      nearest-attackable-target: -1
      follow-parent: -1
      avoid-entity: -1
      temptation: -1
      enderman-look-for-player: -1
  fast-biome-manager-seed-obfuscation:
    enabled: true
    seed-obfuscation-key: -8684531201898316847
  faster-random-generator:
    enabled: true
    enable-for-worldgen: true
    warn-for-slime-chunk: false
    use-legacy-random-for-slime-chunk: true
  faster-structure-gen-future-sequencing: true
  reuse-random-ticking-blockpos: false
  cache-biome:
    enabled: true
    mob-spawning: true
    advancements: true
  optimize-block-entities: true
  optimize-mob-despawn: true
  only-tick-items-in-hand: false
  optimize-mob-spawning: true
  optimize-no-action-time:
    disable-light-check: false
  optimize-player-movement: true
  optimize-random-tick: true
  optimize-waypoint: false
  optimized-powered-rails: true
  reduce-packets:
    reduce-entity-move-packets: true
    reduce-entity-motion-packets: true
    disable-useless-particles: true
  skip-ai-for-non-aware-mob: true
  datapack:
    skip-inactive-entity-for-execute-command: false
  skip-map-item-data-updates-if-map-does-not-have-craftmaprenderer: true
  throttle-hopper-when-full:
    enabled: false
    skip-ticks: 8
  throttle-mob-spawning:
    enabled: false
    monster:
      min-failed: 8
      spawn-chance: 25.0
    creature:
      min-failed: 8
      spawn-chance: 25.0
    ambient:
      min-failed: 8
      spawn-chance: 25.0
    axolotls:
      min-failed: 8
      spawn-chance: 25.0
    underground_water_creature:
      min-failed: 8
      spawn-chance: 25.0
    water_creature:
      min-failed: 8
      spawn-chance: 25.0
    water_ambient:
      min-failed: 8
      spawn-chance: 25.0
  create-snapshot-on-retrieving-blockstate: true
  use-virtual-thread:
    bukkit-async-scheduler: true
    folia-async-scheduler: true
    async-chat-executor: true
    download-pool: true
    auth-pool: true
    paper-configuration-pool: true

fixes:
  vanilla-bug-fix:
    mc-270656: true
    mc-301114: true
    mc-301114-max-entries: 10240
  prevent-moving-into-weak-loaded-chunks:
    enabled: false
    projectiles: false

gameplay-mechanisms:
  afk-command:
    enabled: false
  inventory-overflow-event:
    enabled: false
    listener-class: com.example.package.PlayerInventoryOverflowEvent
  player:
    max-use-item-distance: 1.0000001
  allow-tripwire-dupe: false
  death-item-drop-knockback:
    drop-around: true
    horizontal-force: 0.5
    vertical-force: 0.2
  ice-and-snow-chance: 48
  knockback:
    snowball-knockback-players: false
    egg-knockback-players: false
    can-player-knockback-zombie: true
    flush-location-while-knockback-player: false
    old-blast-protection-explosion-knockback: false
  only-player-pushable: false
  spawner-settings:
    enabled: false
    checks:
      light-level-check: false
      spawner-max-nearby-check: true
      check-for-nearby-players: true
      spawner-block-checks: false
      water-prevent-spawn-check: false
      ignore-spawn-rules: false
    min-spawn-delay: 200
    max-spawn-delay: 800
  use-spigot-item-merging-mechanism: false

network:
  async-switch-state: true
  chat-message-signature: false
  OptimizeNonFlushPacketSending: true
  protocol-support:
    strict-mode: false
    jade-protocol: true
    appleskin-protocol: true
    appleskin-protocol-sync-tick-interval: 20
    asteorbar-protocol: false
    chatimage-protocol: false
    xaero-map-protocol: true
    xaero-map-server-id: -1402571288
    syncmatica-protocol: false
    syncmatica-quota: false
    syncmatica-quota-limit: 40000000
    do-a-barrel-roll-protocol: true
    do-a-barrel-roll-allow-thrusting: true
    do-a-barrel-roll-force-enabled: false
    do-a-barrel-roll-force-installed: false
    do-a-barrel-roll-installed-timeout: 0

misc:
  connection-message:
    join:
      enabled: true
      message: default
    quit:
      enabled: true
      message: default
  disable-world-data-saving:
    worlds: []
  including-5s-in-get-tps: true
  lag-compensation:
    enabled: true
    enable-for-water: true
    enable-for-lava: true
  remove-change-non-editable-sign-warning: false
  remove-spigot-check-bungee-config: false
  secure-seed:
    enabled: false
  sentry:
    dsn: ''
    log-level: WARN
    only-log-thrown: true
  rebrand:
    server-mod-name: DaBusiness.cloud
    server-gui-name: Da Business
  message:
    unknown-command: default
  vanilla-username-check:
    remove-all-check: false
    enforce-skull-validation: true
    allow-old-players-join: false
    use-username-regex: false
    username-regex: ^[a-zA-Z0-9_.]*$

chunk-loading:
  no-tick-view-distance: 12
